spring:
  profiles:
    active: local
  
---
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true
    
---
spring:
  profiles: local
  mvc: 
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    async:
      request-timeout: 60000
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@112.217.167.123:31521:orcl
    username: WATER
    password: WATER
logging: 
#  config: classpath:logback.xml
  file: logs/spring-boot-logging.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level: 
    org.springframework.web: INFO
    root: INFO
server: 
  context-path: /krf
  
---
spring: 
  profiles: prod
  mvc:
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    async:
      request-timeout: 60000
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@112.217.167.123:31521:orcl
    username: WATER
    password: WATER
logging: 
#  config: classpath:logback.xml
  pattern: 
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level: 
    org.springframework.web: ERROR
  file: logs/spring-boot-logging.log 
    
server: 
  context-path: /krf
    

