spring: 
    profiles: 
      active: local
    
server:
  session:
    timeout: 120 
    
mybatis: 
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true
     
logging:
  level:
    org.springframework.web: DEBUG
    com.ce.krf.biz.controller: DEBUG
    com.spring.mybatis : DEBUG
    com.ce.krf : DEBUG
    
---
spring:
  profiles: local
  mvc: 
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp 
    async:
      request-timeout: 60000
  datasource: 
  #jndi-name: krf_db 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@112.217.167.123:31720:STKDIV
    username: WATER2018
    password: WATER2018
    tomcat:
      max-idle: 40
      min-idle: 2
      test-while-idle: true
      validation-query2: select 1 from dual      default-auto-commit: false
logging: 
#  config: classpath:logback.xml
  file: logs/spring-boot-logging.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level: 
    org.springframework.web: INFO
    root: INFO
server: 
  context-path: /krf

print: 
  img: 
     path: C:/arcgisserver/directories/arcgisoutput/customPrintTask/
---
spring:
  profiles: local2
  mvc: 
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    async:
      request-timeout: 60000
  datasource: 
  #jndi-name: krf_db 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@112.217.167.123:31720:STKDIV
    username: WATER_2
    password: WATER_2
    tomcat:
      max-idle: 40
      min-idle: 2
      test-while-idle: true
      validation-query2: select 1 from dual
      default-auto-commit: false
logging: 
#  config: classpath:logback.xml
  file: logs/spring-boot-logging.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level: 
    org.springframework.web: INFO
    root: INFO
server: 
  context-path: /krf

print: 
  img: 
     path: C:/arcgisserver/directories/arcgisoutput/customPrintTask/
---
spring: 
  profiles: prod-in
  mvc:
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    async:
      request-timeout: 60000
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.101.95.15:51521:weis
    username: WATER
    password: WATER123
    tomcat:
      max-idle: 30
      min-idle: 1
      test-while-idle: true
      validation-query: select 1 from dual
logging: 
#  config: classpath:logback.xml
  pattern: 
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level: 
    org.springframework.web: ERROR
  file: logs/spring-boot-logging.log 
    
server: 
  context-path: /krf
  
print: 
  img: 
     path: C:/arcgisserver/directories/arcgisoutput/customPrintTask/prod

---
spring: 
  profiles: prod-out
  mvc:
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    async:
      request-timeout: 60000
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@2.2.2.69:1521:KRFDB
    username: water 
    password: water123
    tomcat:
      max-idle: 30
      min-idle: 1
      test-while-idle: true
      validation-query: select 1 from dual
logging: 
#  config: classpath:logback.xml
  pattern: 
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level: 
    org.springframework.web: ERROR
  file: logs/spring-boot-logging.log 
    
server: 
  context-path: /krf
  
print: 
  img: 
     path: C:/arcgisserver/directories/arcgisoutput/customPrintTask/prod
     
---
spring: 
  profiles: prod-in-new
  mvc:
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    async:
      request-timeout: 60000
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.101.95.195:1521/WEIS
    username: water 
    password: water123
    tomcat:
      max-idle: 30
      min-idle: 1
      test-while-idle: true
      validation-query: select 1 from dual
logging: 
#  config: classpath:logback.xml
  pattern: 
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level: 
    org.springframework.web: ERROR
  file: logs/spring-boot-logging.log 
    
server: 
  context-path: /krf
  
print: 
  img: 
     path: C:/arcgisserver/directories/arcgisoutput/customPrintTask/prod

